apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-summarizer
  namespace: k-ndp-d01-ndp-monitor-llm-test-ns   # namespace где запускаются поды
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-summarizer
  namespace: k-ndp-d01-ndp-monitor-llm-test-ns
subjects:
  - kind: ServiceAccount
    name: airflow-multiinstance                    # SA из ошибки
    namespace: k-ndp-d01-ndp-airflow-monlog        # namespace где живёт Airflow
roleRef:
  kind: Role
  name: airflow-summarizer
  apiGroup: rbac.authorization.k8s.io
