namespace: k-ndp-d01-ndp-monitor-llm-test-ns

storage:
  className: nfs
  data:
    size: 10Gi
  runs:
    size: 50Gi

rbac:
  serviceAccountName: airflow-multiinstance
  airflowNamespace: k-ndp-d01-ndp-airflow-monlog
