apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: summarizer-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
  storageClassName: {{ .Values.storage.className }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: summarizer-runs
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.runs.size }}
  storageClassName: {{ .Values.storage.className }}
