apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "general-summarizer.dataPVC" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "general-summarizer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
  storageClassName: {{ .Values.storage.className }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "general-summarizer.runsPVC" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "general-summarizer.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.runs.size }}
  storageClassName: {{ .Values.storage.className }}
