apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: general-summarizer
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: general-summarizer
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Values.rbac.airflowNamespace }}
roleRef:
  kind: Role
  name: general-summarizer
  apiGroup: rbac.authorization.k8s.io
